Updated the standard view and made some changes to how the information is sent to the callback modules.
The start script has been modified a little to give possibility to
specify name/sname for the ntop node itself and the cookie to use to
connect.

diff --git a/ntop b/ntop
--- a/ntop
+++ b/ntop
@@ -28,10 +28,13 @@ do
     esac
 done
 
-erl -noinput -hidden -pa ebin/ -pa ../cecho/ebin/ +A 200 +Bc -eval "ntop:start('${TARGETNODE}',[])" $NAME $COOKIE $@
+erl -noinput -hidden -pa ebin/ -pa ../cecho/ebin/ +A 20 +Bc -eval "ntop:start('${TARGETNODE}',[])" $NAME $COOKIE $@
 
 CODE=$?
-if [[ $CODE == 101 ]]; then
-    echo "Unable to connect to '${NODE}', check nodename, cookie and network."
+if [[ $CODE -eq 101 ]]; then
+    echo "Unable to connect to '${TARGETNODE}', check nodename, cookie and network."
     exit 2
+elif [[ $CODE -gt 0 ]]; then
+    echo "Something wrong. Code: ${CODE}"
+    exit $CODE
 fi
